/* Config.h.   Generated by CMake */
#define HAVE_TBB           1
#define HAVE_STD_UNIQUE_PTR 1
#define ENABLE_FLAT_FIELDMAP       1
#define HAVE_STD_SHARED_PTR        1
#define ENABLE_TBB_ALLOCATOR    1
